<!-- calling database -->
<?php
   class MyDB extends SQLite3 {
      function __construct() {
         $this->open('poem_cluster.db');
      }
   }
   $db = new MyDB();
   if(!$db) {
      echo $db->lastErrorMsg();
   } else {
      echo "";
   }
?>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
      .fade-in {
          -webkit-animation: fade-in 0.7s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
          animation: fade-in 0.7s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
      }

      /* ----------------------------------------------
      * Generated by Animista on 2020-12-31 13:41:8
      * Licensed under FreeBSD License.
      * See http://animista.net/license for more info. 
      * w: http://animista.net, t: @cssanimista
      * ---------------------------------------------- */

      /**
      * ----------------------------------------
      * animation fade-in
      * ----------------------------------------
      */
      @-webkit-keyframes fade-in {
        0% {
          opacity: 0;
        }
        100% {
          opacity: 1;
        }
      }
      @keyframes fade-in {
        0% {
          opacity: 0;
        }
        100% {
          opacity: 1;
        }
      }

  div.scroll {
        
        overflow-x: hidden;
        overflow-y: auto;
        text-align: center;
        padding: 30px;
      }

      
.bg-image {

    background-image: url("img/bg5.jpg");
    background-repeat: no-repeat;
    background-size: cover;
    background-position: center;
    background-position-y: 60%;
    background-position-x: 20%;

   }

      h1
      {
        font-family: 'Rouge Script', cursive;
        font-size: 400%;
        color:white;  
      }
     
.search-container
    {
    float: right;
    }

    input[type=text] 
    {
     padding: 10px;
    margin-top: 8px;
     font-size: 17px;
    border: none;
    }

    .search-container button
     {
  float: right;
  padding: 14px 10px;
  margin-top: 8px;
  margin-right: 16px;
  background: #696969;
  font-size: 17px;
  border: none;
  cursor: pointer;
    }

.search-container button:hover 
{
  background: #ccc;
}

@media screen and (max-width: 600px) 
{
  .search-container {
    float: none;
  }

   input[type=text], .search-container button 
   {
    float: none;
    display: block;
    text-align: left;
    width: 100%;
    margin: 0;
    padding: 20px;
  }

   input[type=text] 
   {
    border: 1px solid #ccc;  
  }
}

.solid{
  background-color: rgba(0, 0, 0, 0.5);
  
}

    </style>

    <title>POEM RECOMMENDER SYSTEM</title>
    <link rel="stylesheet" href="mystyle.css">
    
</head>


  <body class="overflow-hidden fade-in">
<div class="bg-image">
  <div class="container-fluid" style="height: 40vh;">
    <div class="solid"> <br><br><br><br><br>
      <h1><b><center>POEM RECOMMENDER SYSTEM<center></b></h1>
    </div>

    <!-- Search button -->
      <div class="search-container">
<form action="content/poem_rec.php" method="post">
    <input type="text" placeholder="Search by poem name.." name="poem" required></input>
    <button type="submit" name="submit" /><i class="fa fa-search"></i></button>  
</form>
</div>
   
    <br><br><br><br>

 <div class="scroll">
<div class="container custom-container shadow-lg rounded bg-white border-top-0">
  <h2 class="pt-4"><center>Poems That Will Save Your Life!</center></h2>

  <div class="row pt-2 mb-4">
      <div class="col-lg-4 mb-3 mb-lg-0">
          <div class="hover hover-3 text-white rounded"><img src="img/phoenix.jpg" alt="">
            <div class="hover-overlay"></div>
            <div class="hover-3-content px-5 py-4">
              <h3 class="hover-3-title text-uppercase font-weight-bold mb-1"><span class="font-weight-light"></span>The Phoenix and the Turtle</h3>
              <a class="hover-3-description btn btn-outline-light" href="content/phoenix.php" role="button">READ</a> 
          </div>
          </div>
        </div>
      <div class="col-lg-4 mb-3 mb-lg-0">
          <div class="hover hover-3 text-white rounded"><img src="img/epilogue.jpg" alt="">
            <div class="hover-overlay"></div>
            <div class="hover-3-content px-5 py-4">
              <h3 class="hover-3-title text-uppercase font-weight-bold mb-1"><span class="font-weight-light"></span>An Epilogue to the Above</h3>
            <a class="hover-3-description btn btn-outline-light" href="content/epilogue.php" role="button">READ</a>  
            </div>
          </div>
        </div>
      <div class="col-lg-4 mb-3 mb-lg-0">
          <div class="hover hover-3 text-white rounded"><img src="img/protha.jpg" alt="">
            <div class="hover-overlay"></div>
            <div class="hover-3-content px-5 py-4">
              <h3 class="hover-3-title text-uppercase font-weight-bold mb-1"><span class="font-weight-light"></span>Prothalamion</h3>
              <a class="hover-3-description btn btn-outline-light" href="content/protha.php" role="button">READ</a>
            </div>
          </div>
        </div>  
  </div>
  <!-- ___________________________________________________ -->
    <div class="row pt-2 mb-4">
      <div class="col-lg-4 mb-3 mb-lg-0">
          <div class="hover hover-3 text-white rounded"><img src="img/faerie.jpg" alt="">
            <div class="hover-overlay"></div>
            <div class="hover-3-content px-5 py-4">
              <h3 class="hover-3-title text-uppercase font-weight-bold mb-1"><span class="font-weight-light"></span>from The Faerie Queene: Book I, Canto I</h3>
              <a class="hover-3-description btn btn-outline-light" href="content/faerie.php" role="button">READ</a>
          </div>
          </div>
        </div>
      <div class="col-lg-4 mb-3 mb-lg-0">
          <div class="hover hover-3 text-white rounded"><img src="img/custom.jpg" alt="">
            <div class="hover-overlay"></div>
            <div class="hover-3-content px-5 py-4">
              <h3 class="hover-3-title text-uppercase font-weight-bold mb-1"><span class="font-weight-light"></span>Sonnet 16</h3>
              <a class="hover-3-description btn btn-outline-light" href="content/sonnet16.php" role="button">READ</a>
            </div>
          </div>
        </div>
      <div class="col-lg-4 mb-3 mb-lg-0">
          <div class="hover hover-3 text-white rounded"><img src="img/apparition.jpg" alt="">
            <div class="hover-overlay"></div>
            <div class="hover-3-content px-5 py-4">
              <h3 class="hover-3-title text-uppercase font-weight-bold mb-1"><span class="font-weight-light"></span>The Apparition</h3>
              <a class="hover-3-description btn btn-outline-light" href="content/apparition.php" role="button">READ</a>
            </div>
          </div>
        </div>  
  </div>
<!-- ___________________________________________________ -->
  <div class="row pt-2 mb-4">
      <div class="col-lg-4 mb-3 mb-lg-0">
          <div class="hover hover-3 text-white rounded"><img src="img/epithalamion.png" alt="">
            <div class="hover-overlay"></div>
            <div class="hover-3-content px-5 py-4">
              <h3 class="hover-3-title text-uppercase font-weight-bold mb-1"><span class="font-weight-light"></span>Epithalamion</h3>
              <a class="hover-3-description btn btn-outline-light" href="content/epithalamion.php" role="button">READ</a>
          </div>
          </div>
        </div>
      <div class="col-lg-4 mb-3 mb-lg-0">
          <div class="hover hover-3 text-white rounded"><img src="img/hero.jpg" alt="">
            <div class="hover-overlay"></div>
            <div class="hover-3-content px-5 py-4">
              <h3 class="hover-3-title text-uppercase font-weight-bold mb-1"><span class="font-weight-light"></span>Hero and Leander</h3>
              <a class="hover-3-description btn btn-outline-light" href="content/hero.php" role="button">READ</a>
            </div>
          </div>
        </div>
      <div class="col-lg-4 mb-3 mb-lg-0">
          <div class="hover hover-3 text-white rounded"><img src="img/orpheus.jpg" alt="">
            <div class="hover-overlay"></div>
            <div class="hover-3-content px-5 py-4">
              <h3 class="hover-3-title text-uppercase font-weight-bold mb-1"><span class="font-weight-light"></span>Song: Orpheus with his lute made trees</h3>
              <a class="hover-3-description btn btn-outline-light" href="content/orpheus.php" role="button">READ</a>
            </div>
          </div>
        </div>  
  </div>
  <!-- ___________________________________________________ -->
  <div class="row pt-2 mb-4">
      <div class="col-lg-4 mb-3 mb-lg-0">
          <div class="hover hover-3 text-white rounded"><img src="img/apparition.jpg" alt="">
            <div class="hover-overlay"></div>
            <div class="hover-3-content px-5 py-4">
              <h3 class="hover-3-title text-uppercase font-weight-bold mb-1"><span class="font-weight-light"></span>Break of Day</h3>
              <a class="hover-3-description btn btn-outline-light" href="content/break.php" role="button">READ</a>
          </div>
          </div>
        </div>
      <div class="col-lg-4 mb-3 mb-lg-0">
          <div class="hover hover-3 text-white rounded"><img src="img/custom.jpg" alt="">
            <div class="hover-overlay"></div>
            <div class="hover-3-content px-5 py-4">
              <h3 class="hover-3-title text-uppercase font-weight-bold mb-1"><span class="font-weight-light"></span>My Picture Left in Scotland</h3>
              <a class="hover-3-description btn btn-outline-light" href="content/picture.php" role="button">READ</a>
            </div>
          </div>
        </div>
      <div class="col-lg-4 mb-3 mb-lg-0">
          <div class="hover hover-3 text-white rounded"><img src="img/relic.jpg" alt="">
            <div class="hover-overlay"></div>
            <div class="hover-3-content px-5 py-4">
              <h3 class="hover-3-title text-uppercase font-weight-bold mb-1"><span class="font-weight-light"></span>The Relic</h3>
              <a class="hover-3-description btn btn-outline-light" href="content/relic.php" role="button">READ</a>
            </div>
          </div>
        </div>  
  </div>
  <!-- ___________________________________________________ -->
  <div class="row pt-2 mb-4">
      <div class="col-lg-4 mb-3 mb-lg-0">
          <div class="hover hover-3 text-white rounded"><img src="img/ring.jpeg" alt="">
            <div class="hover-overlay"></div>
            <div class="hover-3-content px-5 py-4">
              <h3 class="hover-3-title text-uppercase font-weight-bold mb-1"><span class="font-weight-light"></span>Ring Out Your Bells</h3>
              <a class="hover-3-description btn btn-outline-light" href="content/ring.php" role="button">READ</a>
          </div>
          </div>
        </div>
      <div class="col-lg-4 mb-3 mb-lg-0">
          <div class="hover hover-3 text-white rounded"><img src="img/star.jpg" alt="">
            <div class="hover-overlay"></div>
            <div class="hover-3-content px-5 py-4">
              <h3 class="hover-3-title text-uppercase font-weight-bold mb-1"><span class="font-weight-light"></span>Song: Go and catch a falling star</h3>
              <a class="hover-3-description btn btn-outline-light" href="content/star.php" role="button">READ</a>
            </div>
          </div>
        </div>
      <div class="col-lg-4 mb-3 mb-lg-0">
          <div class="hover hover-3 text-white rounded"><img src="img/neat.jfif" alt="">
            <div class="hover-overlay"></div>
            <div class="hover-3-content px-5 py-4">
              <h3 class="hover-3-title text-uppercase font-weight-bold mb-1"><span class="font-weight-light"></span>Still to be neat, still to be dressed</h3>
              <a class="hover-3-description btn btn-outline-light" href="content/neat.php" role="button">READ</a>
            </div>
          </div>
        </div>  
  </div>
  <!-- ___________________________________________________ -->
</div>
</div><br>
<!-- <button class="button"><span  onclick="window.location='content/poem_rec.php'">CLICK TO GET MORE RECOMMENDATIONS</span></button>
 -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

</body>

</html>




